### PR TITLE
src: introduce uv_reject call win

### PR DESCRIPTION
**Pull request by huseyinacacak-janea**
This PR includes the followings:
1. `uv_reject` is implemented on Windows.
2. `test-tcp-reject.c` is updated to cover Windows.
3. `test-pipe-reject.c` and `test-tcp-reject-accept.c` are added to test different scenarios. If you think these are not necessary you can disable them.
4. If I'm not wrong, UDP cannot accept or reject the connections. Do you think we should still do something there?

Feel free to change anything.

### CODE REVIEW

**Comment by juanarbol** [comment]
Dude, you are the best. Just give me some time. I finish the UNIX implementations and will cherry-pick into my libuv PR. Thanks!

**Comment by juanarbol** [comment]
I'm not a windows developer at all. So, we better put this into the libuv's wall.

**Comment by juanarbol** [comment]
Just as a question. I'm not a fan of "patch sets" would you mind if I mingle this with my commit and put you as a co-author? It would be easier to review and you will appear as co-author of that change in your GH profile as well.

**Comment by huseyinacacak-janea** [comment]
Sure, no problem.

**Comment by juanarbol** [comment]
Hey! Ae we discussed a couple weeks ago, you're co-author of https://github.com/libuv/libuv/pull/4423/commits/50e5309d9f7ff53de7d350ad575a97e807cd9013

Thanks for this contribution, and I'm sorry for being that slow in response.

**Comment by juanarbol** [comment]
I'm closing this, as this is landed already.

**Pull request closed without merging**
